CREATE DATABASE IF NOT EXISTS capricorn;
USE capricorn;

CREATE TABLE IF NOT EXISTS cap_person (
  username VARCHAR(255) PRIMARY KEY,
  mobile VARCHAR(60) NOT NULL,
  hash VARCHAR(255) NOT NULL,
  verified TINYINT NOT NULL DEFAULT 0,
  role VARCHAR(255) NOT NULL DEFAULT 'customer'
);

CREATE TABLE IF NOT EXISTS cap_post (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  author VARCHAR(255) NOT NULL,
  content TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS cap_reply (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  postId INTEGER,
  author VARCHAR(255),
  content TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS cap_log (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  event VARCHAR(255),
  message TEXT
);
